id: 5dc2e24415eb41a3838297b6d9be572e
initial_creation_type: ocr
source_metadata:
  volumes:
    0074285946a74d6e974daa010ffd442c:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: ''
      total_pages: 1853
      volume_number: 25
